### ISSUE TITLE
Time to replace retiring spatial packages

### ISSUE THREAD

**Issue by rsbivand** [vegmod/meteoland#15]
The CRAN release requires **rgdal** and your `spatial_refactor` still suggests **rgdal**, please remove it completely since you are refactoring anyway (hint - depend on the latest **sp** and load with evolution_status 2L - see talk mentioned below to make sp use sf for CRS and transformation).

rgdal, rgeos and maptools will retire during 2023. As is explained in this presentation: https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf, package maintainers should aim to have replaced probably redundant dependencies on these packages by June 2023 (before the northern hemisphere tutorial season), and certainly by October 2023 when the packages will be archived. The presentation was recorded: https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1. Further details in blogs: https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html, and in tabulations on https://github.com/r-spatial/evolution.

**Comment by MalditoBarbudo** [comment]
@rsbivand,

the **rgdal** dependency (in suggests) for the `spatial_refactor` branch is due to maintain compatibility with the previous versions of meteloand during the first half of the year (to give warnings to the users about the changes before completly deprecating). At June, a new version of `meteoland` will be released without any dependency on **rgdal**, **sp**, **rgeos** or **maptools** (nor in depends, nor in suggests).

But we will look into the use of  **sp** with evolution_status 2L, because if we can get rid of **rgdal** dependency the sooner, the better. Thanks a lot for links!

**Comment by rsbivand** [comment]
Thanks! The most recent **sp** on CRAN has `set_evolution_status()` and `get_evolution_status()`, allowing fine-grained control. The presentation links describe the status option: about 43 min into the video, slide 32; it can now be set and reset as **sp** runs. Your branch imports **sf**, so you could simply go for `2L`, but maybe that would affect other loaded packages in workflows, so it may be less invasive to wait. Any experience you gain is of considerable interest!

**Comment by MalditoBarbudo** [comment]
@rsbivand

As per the pdf slides (slide 32), the evolution status can be set also as an environment variable (`_SP_EVOLUTION_STATUS_`). But both sp functions, `set_evolution_status()` and `get_evolution_status()`, they look in a specific environment for this (`envir = .spOptions`).
I'm wrong assuming that setting locally the `_SP_EVOLUTION_STATUS_` environment variable like the following will work for `meteoland` functions without altering other loaded packages or workflows?

```
meteoland_function <- function(...) {
    foo <- withr::with_envvar(
        new = c("_SP_EVOLUTION_STATUS_" = 2L),
        code = {
            # code calling spParams or other sp function requiring rgdal is forced to use `sf` methods
        }
    )
    
    foo |>
      ... # rest of the function, without rgdal related code
}
```

The use of the `.spOptions` environment in the evolution status functions makes me doubt if this approach can be taken or not.

Also, if you prefer having this discussion in other venue (an issue in the `sp` GitHub or another forum) let me know.
Thanks!

**Comment by rsbivand** [comment]
Sorry, I avoid all **withr** candy. Use of the environment variable is mostly in reverse depencency checking, so `_SP_EVOLUTION_STATUS_=2 R CMD `, or possibly `Sys.setenv("_SP_EVOLUTION_STATUS_"= "2")` - environment variables are strings. The **sp** options do not use `base::options()`, they use a sealed environment in the **sp** namespace. The helper functions can read and write that environment.

If one uses the environment variable or the option option, it must be set before **sp** is loaded, as **sp** sets it by looking for the environment variable (or the option option) on load, which set the value for the whole session. If another software component has loaded **sp** already, it has pre-empted the value. This is why the `set`/`get` functions were added, but they have the side effect of changing the value for other packages that might have loaded **sp** earlier. 

So if you just want to check that your package runs under 2, setting the environment variable before R CMD check works, but in code you would need to read the existing status and store it, update status, use **sp**, the revert to the pre-existing status so as not to modify the working conditions of other packages etc.

**Comment by MalditoBarbudo** [comment]
Understood, so something like the following woud be better to use in code, once I've previously checked everything is correct with  R CMD and the environment variable set.

```
function(...) {
    # set temporary the 2L status
    old_evolution_status <- get_evolution_status()
    set_evolution_status(2L)
   # ensure at exit (normal or error) the evolution status is set to the original
    on.exit(set_evolution_status(old_evolution_status))

    # ... function code ...
}
```

Thank you very much for your time and detailed answers.

**Comment by MalditoBarbudo** [comment]
After careful consideration, and given the following:

1. `_SP_EVOLUTION_STATUS_=2 R CMD CHECK` fails due to lack of methods in `sp::geometry` for converting `SpatialMeteorology*`, `SpatialTopography*`, `SpatialInterpolatedData`... custom classes.
1. Using set/get evolution status inside functions is also a no go,  without developing the methods for these classes
1. These classes will be deprecated in June.
1. I prefer not spending time in implementing `sp::geometry` methods for classes that will dissapear.

`rgdal` soft dependency will stay in following versions of `meteoland`, and coming June it will dissapear. Same will happen with the hard dependency on `sp`.

**Comment by rsbivand** [comment]
OK, and thank you for presenting your reasoning.
