### ISSUE TITLE
Error when using "create_meteo_interpolator()"

### ISSUE THREAD

**Issue by JoelMet** [vegmod/meteoland#27]
Hello, 
whenever I try to create an inerplotae object with "create_meteo_interpolator" I get this error message.

`interpolator <- with_meteo(meteoland_meteo_example) %>%
                                create_meteo_interpolator()

i Checking meteorology object...
√ meteorology object ok
i Creating interpolator...
Error in check_join_vars():
! Join columns must be present in data.
x Problem with explicit.
Run rlang::last_trace() to see where the error occurred.
Warning message:
No interpolation parameters provided, using defaults
i Set the params argument to modify parameter default values`

The happende for this code:
`create_meteo_interpolator(with_meteo(meteoland_meteo_example) )`

What am I doing wrong?

**Comment by MalditoBarbudo** [comment]
Hi @JoelMet 

As the examples works both on CRAN checks and in our tests, something must be missing on your session.
First of all, try to update all R packages you have installed with `update.packages()` or using the Packages tab in Rstudio and try again.
If the error persists, please copy and paste here the output of `sessionInfo()` just after the error, for me to be able to check if something is missing.

**Comment by JoelMet** [comment]
Hi @MalditoBarbudo 
thank your for the help. I updated R to version 4.1 and then everything worked. 

I do get a new arror though:
`points_interpolated_2000 <- DE_topo_masked |> 
 interpolate_data(interpolator_2000)
Error in .interpolation_point():
! More than 10% of the points in `spatial_data` fall outside the convex hull of the interpolator object.`

I there any rule regarding the minimum resolution for the topo raster?

![topo_with_stations](https://github.com/emf-creaf/meteoland/assets/19466912/94bd6ca9-1e8c-457c-89d8-312b099351ee)

**Comment by MalditoBarbudo** [comment]
That error is raised not because of the resolution of the topo data, but because the convex hull of the meteo stations present in the interpolator doesn't cover all the topo data, and more than 10% of the topo data is outside the "scope" of the interpolator.
We are being very restrictive with this and we have realized that is best to give a warning instead of an error, and allow the interpolation to perform. For this, a new version of `meteoland` will appear in CRAN shortly, but in the meantime if you want to get rid of this error you can:

1. Install the development version of `meteoland` from github, i.e. `remotes::install_github("emf-creaf/meteoland")`
2. Perform the interpolation, but adding an argument to ignore the convex hull check: `DE_topo_masked |>  interpolate_data(interpolator_2000, ignore_convex_hull_check = TRUE)`.

In theory, this should fix the problem you are facing right now.
